var define = require("node-constants")(exports);

define({
		OPEN_API: '3.0.0',
		SWAGGER_INFO_TITLE: 'API for hardwareservice',
		SWAGGER_INFO_DESCRIPTION: 'This is a REST API application . It retrieves data from Star Connect.',
		SWAGGER_INFO_CONTACT_NAME: 'StarConnect',
		SWAGGER_SERVER_DESCRIPTION: 'Development server',
		PUC: 'Page under construction.',
		PERF: 'please enter required fields.',
		EMAIL_EXIST: 'Email already exist.',
		OSWW: 'Oops! something went wrong.',
		USER_CREATED: 'User created successfully.',
		USER_LIST: 'Users list.',
		COORDINATE_LIST: 'Coordinates list.',
		COORDINATE_ADDED: 'Coordinate added successfully.',		
		SUCCESS_STATUS:'success',
		FAIL_STATUS:'fail',
		INVALID_REQUEST:'Invalid request!',
		NOT_FOUND:'Not found!',
        DEVICE_LIST: 'Device list.',
		DEVICE_SINGLE: 'Device detail.',
        DEVICE_ADDED: 'Device added successfully.',		
		CHART_LIST: 'Chart list.',	
        LOW_ALERT:20,
        HIGH_ALERT:70,
        VEHICLE_ADDED: 'Vehicle added successfully.',
		VEHICLE_UPDATED: 'Vehicle updated successfully.',
        VEHICLE_SINGLE: 'Vehicle detail.',	
        VEHICLE_LIST: 'Vehicle list.',
		VEHICLE_DELETED: 'Vehicle deleted.',
		VEHICLE_NOT_FOUND: 'Vehicle not exist',	
		ALERT_ADDED: 'Alert added successfully.',
		ALERT_UPDATED: 'Alert updated successfully.',
        ALERT_SINGLE: 'Alert detail.',	
        ALERT_LIST: 'Alert list.',
		ALERT_DELETED: 'Alert deleted.',
		ALERT_NOT_FOUND: 'Alert not exist',	
		NOTIFICATION_LIST: 'Notification list.',
        BATTERY_TYPE_LIST: 'Battery type list.',	
        BATTERY_TYPE_ADDED: 'Battery type added successfully.',	
		BATTERY_TYPE_DELETED: 'Battery type deleted successfully',
		BATTERY_TYPE_NOT_FOUND: 'Battery type not found',
        ASSET_TYPE_LIST: 'Asset type list.',	
        ASSET_TYPE_ADDED: 'Asset type added successfully.',	
		ASSET_TYPE_DELETED: 'Asset type deleted successfully',
		ASSET_TYPE_NOT_FOUND: 'Asset type not found',
		ASSET_TYPE_EXIST: 'Asset type already exist.',
        MANUFACTURER_LIST: 'Manufacturer list.',	
        MANUFACTURER_ADDED: 'Manufacturer added successfully.',	
        VEHICLE_MODEL_LIST: 'Vehicle model list.',	
        VEHICLE_MODEL_ADDED: 'Vehicle model added successfully.',
		VEHICLE_MODEL_EXIST: 'Vehicle model already exist.',
		VEHICLE_MODEL_UPDATE: 'Vehicle model update successfully.',
		VEHICLE_MODEL_DELETED: 'Vehicle model deleted',
		VEHICLE_MODEL_SINGLE: 'Vehicle model detail.',
		VEHICLE_MODEL_NOT_FOUND: 'Vehicle model not found',
        VEHICLE_VARIANT_LIST: 'Vehicle variant list.',	
        VEHICLE_VARIANT_ADDED: 'Vehicle variant added successfully.',
        VEHICLE_ID_EXIST: 'Vehicle id already exist.',	
        VEHICLE_ID_NOT_EXIST: 'Vehicle id not exist.',			
		MAIN_DEVICES_LIST: 'Devices list',
		MAIN_DEVICE_ADDED: 'Device added successfully',
		MAIN_DEVICE_DOES_NOT_EXIST: 'Device Does Not Exist',
		MAIN_DEVICE_DETAIL: 'Device Detail',
		MAIN_DEVICE_UPDATED: 'Device updated successfully',
		MAIN_DEVICE_DELETED: 'Device deleted successfully',
		MAIN_DEVICE_SIM_EXIST: 'Already exists',
		MAIN_DEVICE_ALREADY_EXIST: 'Already exists',
		MAIN_DEVICE_NOT_FOUND:'Device not exist',	
		SIMID_NOT_EXIST:'SimId does not exist',	
		SIMID_EXIST:'SimId already exists',		
		SIMID_REQUIRED : 'Sim Id Required',
		IMEI_NOT_EXIST:'IMEI does not exist',	
		IMEI_EXIST:'IMEI already exist',	
		IMEI_REQUIRED : 'IMEI Required',
		DEVICE_MODEL_REQUIRED :'Device Model Required',
        ENTITY_ADDED: 'Entity added successfully.',
		ENTITY_LIST: 'Entity list.',
        ENTITY_SINGLE: 'Entity Detail.',	
		ENTITY_UPDATED: 'Entity update successfully.',	
		ENTITY_EXIST: 'Entity already exist.',	
		ENTITY_DELETED: 'Entity successfully deleted.',	
		ENTITY_NOT_FOUND: 'Entity not found.',			
		HARDWARE_TYPE_LIST	: 'Hardware type list',
		HARDWARE_TYPE_ADDED :'Hardware type added',
		HARDWARE_TYPE_DELETED: 'Hardware type deleted successfully',
		HARDWARE_TYPE_NOT_FOUND: 'Hardware type not found',
		HARDWARE_EXIST: 'Hardware already exist.',
		HARDWARE_UPDATED: 'Hardware updated successfully.',
		HARDWARE_SINGLE: 'Hardware detail.',
		ASSET_TYPE_SINGLE: 'Asset type detail',
		BATERY_TYPE_SINGLE: 'Battery type detail',
		ASSET_TYPE_UPDATED: 'Asset type updated successfully',		
		BATTERY_TYPE_UPDATED: 'Battery type updated successfully',			
		BATTERY_TYPE_EXIST: 'Battery type already exist.',
		TRIP_SUMMAR_LIST: 'Trip summary list',
		VEHICLE_TYPE_LIST: 'Vehicle type list',
		VEHICLE_TYPE_SINGLE: 'Vehicle type detail',
		VEHICLE_TYPE_UPDATED: 'Vehicle type updated successfully',
		VEHICLE_TYPE_ADDED: 'Vehicle type added successfully',
		VEHICLE_TYPE_DELETED: 'Vehicle type deleted',
		VEHICLE_TYPE_NOT_FOUND: 'Vehicle type not found',		
		GEOFENCE_LIST: 'Geofence  list.',	
		GEOFENCE_SINGLE: 'Geofence detail',
        GEOFENCE_ADDED: 'Geofence  added successfully.',	
		GEOFENCE_UPDATED: 'Geofence  updated successfully',
		GEOFENCE_DELETED: 'Geofence  deleted successfully',
		GEOFENCE_NOT_FOUND: 'Geofence type not found',
		GEOFENCE_EXIST: 'Geofence name already exist.',
		IMPORTED: 'successfully imported.',
		FCM_TOKEN_ADDED: 'Token added successfully.',	
		FCM_TOKEN_UPDATED: 'Token updated successfully',

	});